package controller;

public enum Message {
    INVALID_COMMAND,
    SUCCESS,
    //SIGNUP:
    INVALID_USERNAME_FORMAT,
    USERNAME_EXIST,
    SHORT_PASSWORD,
    NO_UPPERCASE,
    NO_LOWERCASE,
    NO_NUMBER,
    NO_SPECIAL,
    WRONG_PASSWORD_CONFIRMATION,
    EMAIL_EXIST,
    INVALID_EMAIL_FORMAT,
    INVALID_QUESTION_NUMBER,
    WRONG_ANSWER_CONFIRMATION,
    EMPTY_FIELD,
    //LOGIN:
    USERNAME_NOT_EXIST,
    INCORRECT_PASSWORD,
    WRONG_RECOVERY_ANSWER,
    LOCKED_ACCOUNT,
    EMPTY_USERNAME_FIELD,
    EMPTY_PASSWORD_FIELD,
    EMPTY_RECOVERY_ANSWER_FIELD,
    WEAK_PASSWORD,
    //TRADE:
    NOT_ENOUGH_GOLD,
    NOT_ENOUGH_AMOUNT,
    NOT_ENOUGH_STORAGE,
    //MARKET:
    INVALID_AMOUNT;

}
